# Generated by Django 5.1.4 on 2025-01-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_dc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidatedobjects',
            name='archived_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consolidatedobjects',
            name='date_last_modified',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objectsfromcao',
            name='archived_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objectsfromcao',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='objectsfromcao',
            name='date_last_modified',
            field=models.DateField(blank=True, null=True),
        ),
    ]
